[project]
name = "sutton-barto-programming"
version = "0.1.0"
description = "Programming solutions to Sutton & Barto"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "tqdm>=4.67.1",
]
